### ISSUE TITLE
Twitter not showing logo from HTML meta-tags in header

### ISSUE THREAD

**Issue by Phrancis** [gendered/gendered#21]
Mentioned to Omayeli on Twitter [here](https://twitter.com/FrancisVeeGee/status/1105275060598816775). 

![image](https://user-images.githubusercontent.com/8539648/54168077-3ee1e500-4443-11e9-8a62-86df33ebd358.png)

Code: https://github.com/gendered/gendered/blob/master/public/index.html

**Comment by oa495** [comment]
https://twitter.com/luciaorlandi/status/1107710653089894400
