### ISSUE TITLE
API is missing

### ISSUE THREAD

**Issue by rileyjshaw** [gendered/gendered#22]
Hi Yeli!

I just went to show a friend this project but it looks like the API is down. The request to [gendered-api.glitch.me/api/words/letter/AZ](gendered-api.glitch.me/api/words/letter/AZ) returns `400`, and I can’t see anything at https://glitch.com/~gendered-api.

I wanted to help out with a pull request, but it looks like that endpoint holds the whole word list. So I’m just leaving this note instead. Let me know if there’s anything I can help with :)

**Comment by oa495** [comment]
Does https://genderedproject.org/ work for you? The API is private right now cause it's on a free plan

**Comment by oa495** [comment]
thanks for opening this :)

**Comment by rileyjshaw** [comment]
It’s working again! I’m not sure why it was returning `400` last week, but I just tried again and it’s up 😊 I’ll close this issue, thank you!

**Comment by rileyjshaw** [comment]
^ and in case this comes up again in the future, I checked that the API was returning `400` across a bunch of different browsers / devices before logging the issue. Maybe the Glitch API temporarily spun down somehow?
